config/routes.rb
Rails.application.routes.draw do
  root "items#index"

  devise_for :users

  resources :items do
    patch "move", on: :member
  end

  get("/cart", { :controller => "items", :action => "cart" })
  post("/add_item_to_cart", { :controller => "items", :action => "add_item_to_cart" })
  post("/remove_item_from_cart", { :controller => "items", :action => "remove_item_from_cart" })

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  validates :name, presence: true

  enum category: {
    fruit: "fruit",
    vegetable: "vegetable",
    dairy: "dairy",
    meat: "meat",
    seafood: "seafood",
    bakery: "bakery",
    household: "household",
    beverages: "beverages",
    alcohol: "alcohol"
  }
  
  enum status: {
    cart: "cart",
    stock: "stock"
  }

  def add_to_cart!
    self.amount += 1
    self.save!
  end

  def remove_from_cart!
    self.amount -= 1
    self.save!
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy move ]

  def add_item_to_cart
    Item.find(params[:item_id]).add_to_cart!

    respond_to do |format|
      flash[:notice] = "Item added to cart"
      format.js {render inline: "location.reload();" }
    end
  end

  def remove_item_from_cart
    Item.find(params[:item_id]).remove_from_cart!

    respond_to do |format|
      flash[:alert] = "Item removed from cart"
      format.js {render inline: "location.reload();" }
    end
  end


  def move
    if @item.stock?
      @item.cart!
    end

    respond_to do |format|
      #format.html { redirect_to items_url, notice: "Item updated" }
    end
  end

  # GET /items or /items.json
  def index
    @items = Item.all
  end

  # GET /items/1 or /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
    respond_to do |format|
      format.html
      format.js
    end
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to item_url(@item), notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to item_url(@item), notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to items_url, notice: "Item was successfully destroyed." }
      format.json { head :no_content }
      format.js
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def item_params
    params.require(:item).permit(:name, :category, :status, :picture, :amount, :user_id)
  end

  def cart
    render({ :template => "items/category.html.erb" })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<li id="<%= dom_id item, :edit %>" class="list-group-item">
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.text_field :picture %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.number_field :amount %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</li>

app/views/items/_item.html.erb
<div class="card-text-center" style="width: 12rem;">
  <h5><%= item.name %></h5>
  <img src="<%= item.picture %>" class="card-img-top" style="width: 150px; height: 150px;">
  <div class="card-body">
    <h5><%= "In cart: " + item.amount.to_s %></h5>
    <% if item.amount && item.amount == 0 %>
      <td><%= button_to 'Add to Cart', {:controller => "items", :action => "add_item_to_cart", :item_id => item.id} ,remote: true,  :method=>:post, :class => "btn btn-outline-primary"  %></td>
    <% else %>
      <td><%= button_to 'Add more', {:controller => "items", :action => "add_item_to_cart", :item_id => item.id} ,remote: true,  :method=>:post, :class => "btn btn-outline-primary"  %></td>
      <td><%= button_to 'Remove', {:controller => "items", :action => "remove_item_from_cart", :item_id => item.id} , remote: true, :method=>:post, class: "btn btn-outline-danger"  %></td>
    <% end %>
    <br>
  </div>
</div>

<%# <%= link_to item, method: :delete, remote: true, class: "btn btn-link" do %>
  <%# <i class="fa-sharp fa-solid fa-trash-can"></i> %>
<%# <% end %>

app/views/items/cart.html.erb
<% empty = true %>
<% current_user.items.each do |item| %>
  <% if item.amount && item.amount > 0 %>
    <div><%= render item %></div>
    <% empty = false %>
  <% end %>
<% end %>

<% if empty %>
  <p style="text-align:center;"><img src="https://www.valeorx.com/static/media/empty-cart.60e68bfd.png" alt="Empty Cart" /></p>
  
<% end %>
<br>
<br>
<h3 style="text-align: center;"><a href="/" class="btn btn-outline-success">Add more items to cart!</a></h3>

app/views/items/destroy.js.erb
$("#<%= dom_id @task %>").fadeOut();

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/edit.js.erb
$("#<%= dom_id @task %>").replaceWith("<%= j(render "tasks/form", task: @task)%>");

app/views/items/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h1 class="h6 text-left">
      <h2>Fruits</h2>
      <hr>
      <div class="row justify-content-md">
        <%= render current_user.items.fruit.order(created_at: :asc) %>
      </ul>
    </div>
    <br>
    <br>
    <div class="col-md-12">
      <h1 class="h6 text-left">
        <h2>Vegetables</h2>
        <hr>
        <div class="row justify-content-md">
          <%= render current_user.items.vegetable.order(created_at: :asc) %>
        </ul>
      </div>
      <br>
      <br>
      <div class="col-md-12">
        <h1 class="h6 text-left">
          <h2>Dairy</h2>
          <hr>
          <div class="row justify-content-md">
            <%= render current_user.items.dairy.order(created_at: :asc) %>
          </ul>
        </div>
        <br>
        <br>
        <div class="col-md-12">
          <h1 class="h6 text-left">
            <h2>Meat</h2>
            <hr>
            <div class="row justify-content-md">
              <%= render current_user.items.meat.order(created_at: :asc) %>
            </ul>
          </div>
          <br>
          <br>
          <div class="col-md-12">
            <h1 class="h6 text-left">
              <h2>Seafood</h2>
              <hr>
              <div class="row justify-content-md">
                <%= render current_user.items.seafood.order(created_at: :asc) %>
              </ul>
            </div>
            <br>
            <br>
            <div class="col-md-12">
              <h1 class="h6 text-left">
                <h2>Bakery</h2>
                <hr>
                <div class="row justify-content-md">
                  <%= render current_user.items.bakery.order(created_at: :asc) %>
                </ul>
              </div>
              <br>
              <br>
              <div class="col-md-12">
                <h1 class="h6 text-left">
                  <h2>Household</h2>
                  <hr>
                  <div class="row justify-content-md">
                    <%= render current_user.items.household.order(created_at: :asc) %>
                  </ul>
                </div>
                <br>
                <br>
                <div class="col-md-12">
                  <h1 class="h6 text-left">
                    <h2>Beverages</h2>
                    <hr>
                    <div class="row justify-content-md">
                      <%= render current_user.items.beverages.order(created_at: :asc) %>
                    </ul>
                  </div>
                  <br>
                  <br>
                  <div class="col-md-12">
                    <h1 class="h6 text-left">
                      <h2>Alcohol</h2>
                      <hr>
                      <div class="row justify-content-md">
                        <%= render current_user.items.alcohol.order(created_at: :asc) %>
                      </ul>
                    </div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @item.category %>
</p>

<p>
  <strong>Status:</strong>
  <%= @item.status %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @item.picture %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @item.amount %>
</p>

<p>
  <strong>User:</strong>
  <%= @item.user_id %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Items</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= render "shared/cdn_assets" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="mb-5">
    <%= render "shared/navbar" %>
    
    <div class="container">
      <%= render "shared/flash_messages" %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_cdn_assets.html.erb
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/js/all.min.js"></script>

app/views/shared/_flash_messages.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert.present? %>
  <div class="alert alert-warning" role="alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light mb-3">
  <div class="container">
    <a class="navbar-brand" href="/">Items</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a href="/cart"><i class="fa-solid fa-cart-shopping"></i></a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      </ul>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        </ul>
        <ul class="navbar-nav mb-2 mb-lg-0">
          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Log in', new_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>